Django initial settings
com-maeng/cali pull request #93
Opened 2024-11-27 13:00 UTC by AMinSC

- 장고 비밀 키 숨기기
- 도커 컴포즈 설정 수정
- 장고 settings, asgi, wsgi manage 수정
- 앱 기본 설정
  - urls 경로 지정
  - app 지정
  - 지역 언어 및 시간 설정

2024-11-29 04:29 UTC, com-maeng requested changes
디렉토리명 변경이 일부 안 된 게 있어서, 제가 바로 변경 후 merge 해놓겠습니다!
이후 소스 코드 변경된 것들 다시 PR 부탁드릴게요 😭

2024-11-29 04:29 UTC, com-maeng commented on backend/cali_backend/urls.py
여기

2024-11-29 04:40 UTC, com-maeng commented
cali_backend 모듈명 픽스 완료입니다~

2024-11-30 03:50 UTC, com-maeng reviewed
확인 부탁드립니다!

2024-11-30 03:50 UTC, com-maeng commented on backend/backend/settings.py
> +    'DJANGO_KEY') or 'django-insecure-637t=(5msymtqj^ln&vx6hgfxm%e31kvh%m^ebhw2^^a-&b(k^'
> 'django-insecure-637t=(5msymtqj^ln&vx6hgfxm%e31kvh%m^ebhw2^^a-&b(k^'

요거는 개발환경용 key 인가요?

2024-11-30 04:20 UTC, AMinSC commented on backend/backend/settings.py
> +    'DJANGO_KEY') or 'django-insecure-637t=(5msymtqj^ln&vx6hgfxm%e31kvh%m^ebhw2^^a-&b(k^'
넵 맞습니다~!

2024-11-30 09:16 UTC, com-maeng approved these changes

2024-11-30 09:17 UTC, merged